### ISSUE TITLE
[FEATURE] 사이드바 마크업 및 스타일링

### ISSUE THREAD

**Issue by eeeyooon** [LikeLion-FE-Final-Project03/car-zip#18]
## 🌳 작업 브랜치

`feature/#18`

## 📝 TASK 개요
사이드바의 HTML, CSS를 만든다.

## ✅ TO DO 및 진행현황

- [x] HTML 완성
- [x] CSS 완성

**Comment by Juhee-Hwang** [comment]
고생하셨습니댜!!
